<Project>
  <PropertyGroup>
    <Version>1.0.2026.724</Version>
    <PackageVersion>1.0.2026.724</PackageVersion>
    <InformationalVersion>1.0.2026.0724</InformationalVersion>
    <AssemblyVersion>1.0.2026.724</AssemblyVersion>
    <FileVersion>1.0.2026.724</FileVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
